name: Maven Build and Test

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw
      - name: Run Tests with Maven Wrapper
        run: ./mvnw --batch-mode test